# -*- coding: utf-8 -*-
"""app_Credit_Risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ST36tAeoez6_rUEgkFHyS4nexFQbxlJB
"""

# credit_risk_app.py
import numpy as np
import streamlit as st
import joblib

# App title
st.title('Credit Risk Prediction Model')

# Fixed model path (no upload)
MODEL_PATH = 'Credit_Risk.pkl'
model = joblib.load(MODEL_PATH)

# --- Input fields ---
# Continuous / numerical features
age = st.number_input('Age', min_value=0.0, step=1.0)
experience = st.number_input('Experience', min_value=-10.0, step=1.0)  # allow negatives
income = st.number_input('Income', min_value=0.0, step=1.0)
family = st.number_input('Family', min_value=1, max_value=4, step=1)
ccavg = st.number_input('CCAvg', min_value=0.0, step=0.1)
education = st.number_input('Education (1=Undergrad, 2=Graduate, 3=Advanced/Professional)',
                            min_value=1, max_value=3, step=1)
mortgage = st.number_input('Mortgage', min_value=0.0, step=1.0)

# --- Boolean inputs (Yes=1, No=0) ---
def yes_no(label):
    return 1 if st.selectbox(label, ['No', 'Yes']) == 'Yes' else 0

securities_account = yes_no('Securities Account')
cd_account = yes_no('CD Account')
online = yes_no('Online')
creditcard = yes_no('CreditCard')

# --- Prediction button ---
if st.button('Predict'):
    # Arrange input features in the correct order
    X = np.array([[
        age, experience, income, family, ccavg, education, mortgage,
        securities_account, cd_account, online, creditcard
    ]], dtype=float)

    # Predict probability of positive class
    prob = model.predict_proba(X)[:, 1][0]

    # Convert probability to a 300–900 "credit risk score"
    score = (1 - prob) * 600 + 300

    st.write('credit risk score:', round(score, 2))